const CONSTANTS = {
	BASE_URL: 'https://ig.gov-cloud.ai',
	SERVICE: 'mobius-gpt-service',
	SERVICE_SYNTH_DATA: 'synthetic-data-generation',
	USER_ID: 'Gaian@123',
	ASSISTANT_ID_UML_TO_PAYLOAD: 'asst_B6ib0zwmwUWFQi5tAyBtoago',
	ASSISTANT_ID_PAYLOAD_TO_PROMPT: 'asst_B6ib0zwmwUWFQi5tAyBtoago',
	TOKEN_OPEN_AI:
		'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',
	RETRIES: 3,
	// ===============
	// baseUrl: 'https://ig.aidtaas.com',
	baseUrl: 'https://ig.gov-cloud.ai',
	fetchInstancesUrl: 'tf-entity-ingestion/v1.0/schemas',
	dataInsertionUrl: 'tf-entity-ingestion/v1.0/schemas',
	token:
		'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3Ny1NUVdFRTNHZE5adGlsWU5IYmpsa2dVSkpaWUJWVmN1UmFZdHl5ejFjIn0.eyJleHAiOjE3MjYxODIzMzEsImlhdCI6MTcyNjE0NjMzMSwianRpIjoiOGVlZTU1MDctNGVlOC00NjE1LTg3OWUtNTVkMjViMjQ2MGFmIiwiaXNzIjoiaHR0cDovL2tleWNsb2FrLmtleWNsb2FrLnN2Yy5jbHVzdGVyLmxvY2FsOjgwODAvcmVhbG1zL21hc3RlciIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmNzFmMzU5My1hNjdhLTQwYmMtYTExYS05YTQ0NjY4YjQxMGQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJIT0xBQ1JBQ1kiLCJzZXNzaW9uX3N0YXRlIjoiYmI1ZjJkMzktYTQ3ZC00MjI0LWFjZGMtZTdmNzQwNDc2OTgwIiwibmFtZSI6ImtzYW14cCBrc2FteHAiLCJnaXZlbl9uYW1lIjoia3NhbXhwIiwiZmFtaWx5X25hbWUiOiJrc2FteHAiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJwYXNzd29yZF90ZW5hbnRfa3NhbXhwQG1vYml1c2R0YWFzLmFpIiwiZW1haWwiOiJwYXNzd29yZF90ZW5hbnRfa3NhbXhwQG1vYml1c2R0YWFzLmFpIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7IkhPTEFDUkFDWSI6eyJyb2xlcyI6WyJIT0xBQ1JBQ1lfVVNFUiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwic2lkIjoiYmI1ZjJkMzktYTQ3ZC00MjI0LWFjZGMtZTdmNzQwNDc2OTgwIiwidGVuYW50SWQiOiJmNzFmMzU5My1hNjdhLTQwYmMtYTExYS05YTQ0NjY4YjQxMGQiLCJyZXF1ZXN0ZXJUeXBlIjoiVEVOQU5UIn0=.FXeDyHBhlG9L4_NCeSyHEaNEBVmhFpfSBqlcbhHaPaoydhKcA0BfuyHgxg_32kQk6z5S9IQ7nVKS2ybtOvwo0WyLWwLQchSq7Noa7LooHIMzmeWMQb_bLKtbaOti59zwIdS8CkfGaXut7RUQKISQVWmbUGsVJQa2JkG6Ng_QN0y5hFVksMWPZiXVsofQkJXHXV1CQ3gabhhHKo3BqlJwzpsCKLDfg1-4PmSl1Wqbw03Ef2yolroj5i8FoeHukOQPkwCUHrrNw-ilIp917nqZa89YbCMtDjWyaj8pEH7GJR5vMZPE2WcJPn5dSA1IHVunfatEB1cDAitaFjVNWNnddQ',
};

const UMLTOSCHEMACONSTANTS = {
	BASE_URL: 'https://ig.gov-cloud.ai',
	SERVICE: 'pi-entity-service',
	SERVICE_SYNTH_DATA: 'UML-TO-SCHEMA',
};

let memoryStore = {
	results: [],
	schemas: {},
};

export default { CONSTANTS, UMLTOSCHEMACONSTANTS, memoryStore };
